# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  pghero: <%= ENV['PGHERO'] == '1' %>
  profiler: <%= ENV['PROFILER'] == '1' %>
  force_ssl: <%= ENV['FORCE_SSL'] == 'True' %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  <<: *default
  secret_smtp_password: 123456

test:
  <<: *default
  secret_smtp_password: 123456

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  smtp_user_name: <%= ENV["SMTP_USER_NAME"] %>
  smtp_host: <%= ENV["SMTP_HOST"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  secret_smtp_password: <%= ENV["SECRET_SMTP_PASSWORD"] %>
